option(ASTREA_ENABLE_SANITIZERS "Enable AddressSanitizer and UndefinedBehaviorSanitizer" OFF)
option(ASTREA_ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(ASTREA_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(ASTREA_ENABLE_TSAN "Enable ThreadSanitizer" OFF)

if(ASTREA_ENABLE_SANITIZERS)
    set(ASTREA_ENABLE_ASAN ON CACHE BOOL "Enable AddressSanitizer" FORCE)
    set(ASTREA_ENABLE_UBSAN ON CACHE BOOL "Enable UndefinedBehaviorSanitizer" FORCE)
endif()

function(astrea_enable_sanitizers target)
    set(sanitizers "")
    if(ASTREA_ENABLE_ASAN)
        list(APPEND sanitizers "address")
    endif()
    if(ASTREA_ENABLE_UBSAN)
        list(APPEND sanitizers "undefined")
    endif()
    if(ASTREA_ENABLE_TSAN)
        list(APPEND sanitizers "thread")
    endif()
    if(sanitizers)
        list(JOIN sanitizers "," SAN_FLAGS)
        target_compile_options(${target} PRIVATE -fsanitize=${SAN_FLAGS} -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=${SAN_FLAGS})
    endif()
endfunction()
