option(ASTREA_ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(ASTREA_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(ASTREA_DOCK_ENABLE_SANITIZERS "Enable ASan and UBSan for Dock" OFF)

function(dock_enable_sanitizers target)
    if(NOT MSVC)
        set(flags)
        if(ASTREA_DOCK_ENABLE_SANITIZERS OR ASTREA_ENABLE_ASAN)
            list(APPEND flags address)
        endif()
        if(ASTREA_DOCK_ENABLE_SANITIZERS OR ASTREA_ENABLE_UBSAN)
            list(APPEND flags undefined)
        endif()
        if(flags)
            list(JOIN flags "," sanitizer_flags)
            target_compile_options(${target} PRIVATE -fsanitize=${sanitizer_flags} -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=${sanitizer_flags})
        endif()
    endif()
endfunction()
