option(ASTREA_ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(ASTREA_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(ASTREA_ENABLE_TSAN "Enable ThreadSanitizer" OFF)

function(astrea_enable_sanitizers target)
    set(flags)
    if(ASTREA_ENABLE_ASAN)
        list(APPEND flags address)
    endif()
    if(ASTREA_ENABLE_UBSAN)
        list(APPEND flags undefined)
    endif()
    if(ASTREA_ENABLE_TSAN)
        list(APPEND flags thread)
    endif()
    if(flags)
        target_compile_options(${target} PRIVATE -fsanitize=${flags})
        target_link_options(${target} PRIVATE -fsanitize=${flags})
    endif()
endfunction()
